package com.funlisten.service.db.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.funlisten.business.download.model.bean.ZYDownloadEntity;
import com.funlisten.business.login.model.bean.ZYUser;
import com.funlisten.business.play.model.bean.ZYPlayHistory;
import com.funlisten.business.search.model.bean.ZYSearchHistory;
import com.funlisten.business.share.model.bean.ZYMarkBean;

import com.funlisten.service.db.entity.ZYDownloadEntityDao;
import com.funlisten.service.db.entity.ZYUserDao;
import com.funlisten.service.db.entity.ZYPlayHistoryDao;
import com.funlisten.service.db.entity.ZYSearchHistoryDao;
import com.funlisten.service.db.entity.ZYMarkBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig zYDownloadEntityDaoConfig;
    private final DaoConfig zYUserDaoConfig;
    private final DaoConfig zYPlayHistoryDaoConfig;
    private final DaoConfig zYSearchHistoryDaoConfig;
    private final DaoConfig zYMarkBeanDaoConfig;

    private final ZYDownloadEntityDao zYDownloadEntityDao;
    private final ZYUserDao zYUserDao;
    private final ZYPlayHistoryDao zYPlayHistoryDao;
    private final ZYSearchHistoryDao zYSearchHistoryDao;
    private final ZYMarkBeanDao zYMarkBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        zYDownloadEntityDaoConfig = daoConfigMap.get(ZYDownloadEntityDao.class).clone();
        zYDownloadEntityDaoConfig.initIdentityScope(type);

        zYUserDaoConfig = daoConfigMap.get(ZYUserDao.class).clone();
        zYUserDaoConfig.initIdentityScope(type);

        zYPlayHistoryDaoConfig = daoConfigMap.get(ZYPlayHistoryDao.class).clone();
        zYPlayHistoryDaoConfig.initIdentityScope(type);

        zYSearchHistoryDaoConfig = daoConfigMap.get(ZYSearchHistoryDao.class).clone();
        zYSearchHistoryDaoConfig.initIdentityScope(type);

        zYMarkBeanDaoConfig = daoConfigMap.get(ZYMarkBeanDao.class).clone();
        zYMarkBeanDaoConfig.initIdentityScope(type);

        zYDownloadEntityDao = new ZYDownloadEntityDao(zYDownloadEntityDaoConfig, this);
        zYUserDao = new ZYUserDao(zYUserDaoConfig, this);
        zYPlayHistoryDao = new ZYPlayHistoryDao(zYPlayHistoryDaoConfig, this);
        zYSearchHistoryDao = new ZYSearchHistoryDao(zYSearchHistoryDaoConfig, this);
        zYMarkBeanDao = new ZYMarkBeanDao(zYMarkBeanDaoConfig, this);

        registerDao(ZYDownloadEntity.class, zYDownloadEntityDao);
        registerDao(ZYUser.class, zYUserDao);
        registerDao(ZYPlayHistory.class, zYPlayHistoryDao);
        registerDao(ZYSearchHistory.class, zYSearchHistoryDao);
        registerDao(ZYMarkBean.class, zYMarkBeanDao);
    }
    
    public void clear() {
        zYDownloadEntityDaoConfig.clearIdentityScope();
        zYUserDaoConfig.clearIdentityScope();
        zYPlayHistoryDaoConfig.clearIdentityScope();
        zYSearchHistoryDaoConfig.clearIdentityScope();
        zYMarkBeanDaoConfig.clearIdentityScope();
    }

    public ZYDownloadEntityDao getZYDownloadEntityDao() {
        return zYDownloadEntityDao;
    }

    public ZYUserDao getZYUserDao() {
        return zYUserDao;
    }

    public ZYPlayHistoryDao getZYPlayHistoryDao() {
        return zYPlayHistoryDao;
    }

    public ZYSearchHistoryDao getZYSearchHistoryDao() {
        return zYSearchHistoryDao;
    }

    public ZYMarkBeanDao getZYMarkBeanDao() {
        return zYMarkBeanDao;
    }

}
